# Generated by Django 4.1.3 on 2022-11-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('authors', models.CharField(max_length=255, verbose_name='authors')),
                ('dbid', models.CharField(max_length=255, verbose_name='id')),
            ],
        ),
    ]
