# Generated by Django 4.1.3 on 2022-11-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='Docu',
            field=models.CharField(max_length=255, null=True, verbose_name='doc'),
        ),
        migrations.AddField(
            model_name='excel',
            name='Keyw',
            field=models.CharField(max_length=255, null=True, verbose_name='key'),
        ),
        migrations.AddField(
            model_name='excel',
            name='Source',
            field=models.CharField(max_length=255, null=True, verbose_name='Source'),
        ),
    ]
